version: '3.8'

services:
  gateway:
    image: com.pegallardo/gateway-api:latest
    ports:
      - '8080:8080'
    depends_on:
      - prediction
      - shared-libraries
    networks:
      - betting-network

  prediction:
    image: com.pegallardo/prediction-api:latest
    ports:
      - '8081:8081'
    depends_on:
      - shared-libraries
    networks:
      - betting-network

  stock-betting:
    image: com.pegallardo/stock-betting-api:latest
    ports:
      - '8082:8082'
    depends_on:
      - shared-libraries
    networks:
      - betting-network

  football-betting:
    image: com.pegallardo/football-betting-api:latest
    ports:
      - '8083:8083'
    depends_on:
      - shared-libraries
    networks:
      - betting-network

  shared-libraries:
    image: com.pegallardo/shared-libraries:latest
    networks:
      - betting-network

networks:
  betting-network:
    driver: bridge
